stages:

  tune:
    # cmd: python src/stages/tune.py --config params.yaml
    cmd: ray job submit --working-dir $PWD -- python src/stages/tune.py --config params.yaml
    params:
    - tune
    outs:
    - ${tune.results_dir}/best_params.yaml:
        cache: false
        persist: true

  train:
    # cmd: python src/stages/train.py --config params.yaml
    cmd: ray job submit --working-dir $PWD -- python src/stages/train.py --config params.yaml
    params:
    - train
    deps:
    - ${tune.results_dir}/best_params.yaml
    outs:
    - ${train.results_dir}/model.pth

plots:
  - results/tune/plots/images
  - training_iteration vs accuracy:
      template: linear
      x: training_iteration
      y:
        results/train/train_metrics.csv: accuracy


